More flexible command line options. Add option to only read settings

diff --git a/set-st-bw/set-st-bw b/set-st-bw/set-st-bw
--- a/set-st-bw/set-st-bw
+++ b/set-st-bw/set-st-bw
@@ -11,20 +11,58 @@
 # curl
 
 ## Configurables:
-#CONFIGFILE=/etc/syncthing/set-st-bw.cfg
 CONFIGFILE=/etc/syncthing/set-st-bw.cfg
 JQPATH=`which jq`
 CURLPATH=`which curl`
 ##
 
-function bail()
-{
+VERBOSE=0
+DONOTWRITE=0
+
+function bail() {
   echo ERROR: "$*"
   exit 1
 }
 
-if [ "$#" -ne 2 ] ; then
-  bail "USAGE: $0 [down rate] [up rate]"
+function usage() {
+  echo "USAGE: $0 -nv -c CONFIGFILE -d DOWN-RATE -u UP-RATE "
+  echo "  -c Path to configuration file."
+  echo "  -n Make no changes, only print the current settings."
+  echo "  -d Set maxRecvKbps. Not required if -n is used."
+  echo "  -u Set maxSendKbps. Not required if -n is used."
+  echo "  -v Verbose output. Useful only for troubleshooting."
+}
+
+while getopts 'd:u:c:nv' OPT
+do
+  case $OPT in
+    d)
+      DOWN=".[].options.maxRecvKbps=$OPTARG|"
+    ;;
+    u)
+      UP=".[].options.maxSendKbps=$OPTARG|"
+    ;;
+    n)
+      DONOTWRITE=1
+    ;;
+    v)
+      VERBOSE=1
+    ;;     
+    c)
+      CONFIGFILE="$OPTARG" 
+    ;;         
+    ?)
+      usage
+      bail "Unknown option: $OPT"
+    ;;
+  esac
+done
+
+if [ "$DONOTWRITE" -eq 0 ] ; then
+  if [ -z "$DOWN" -a -z "$UP" ] ; then
+    usage
+    bail "The -d and/or -u options are required"
+  fi
 fi
 
 if [ ! -r "$CONFIGFILE" ] ; then
@@ -32,32 +70,43 @@ if [ ! -r "$CONFIGFILE" ] ; then
 fi
 
 . $CONFIGFILE
-DOWN=$1
-UP=$2
 
 tmpcfg1=`tempfile`
 tmpcfg2=`tempfile`
 cooks=`tempfile`
 
-CMD="$CURLPATH --cookie-jar $cooks  $INSECURE -s "
+CURLCMD="$CURLPATH --cookie-jar $cooks -s --retry 5"
+
 if [ "$VERBOSE" -eq 1 ] ; then
-  CMD="$CMD -v "
+  CURLCMD="$CURLCMD -v "
+fi
+
+if [ "$INSECURE" -eq 1 ] ; then
+  CURLCMD="$CURLCMD --insecure "
 fi
 
 
-$CMD -o $tmpcfg1 $URL/rest/system/config \
+$CURLCMD -o $tmpcfg1 $URL/rest/system/config \
   || bail "CURL error $?. Unable to download config"
 
-$JQPATH -s  ".[].options.maxRecvKbps=$DOWN|.[].options.maxSendKbps=$UP|.[0]"  $tmpcfg1 > $tmpcfg2 \
-  || bail "Unable to alter JSON config"
+if [ "$DONOTWRITE" = 1 ] ; then
+  echo -n maxRecvKbps=
+  $JQPATH -s  ".[].options.maxRecvKbps"  $tmpcfg1 \
+    || bail "Unable to read config"
+  echo -n maxSendKbps=
+  $JQPATH -s  ".[].options.maxSendKbps"  $tmpcfg1 \
+    || bail "Unable to read config"
+else
+  $JQPATH -s  "$DOWN$UP.[0]"  $tmpcfg1 > $tmpcfg2 \
+    || bail "Unable to alter JSON config"
+  $CURLCMD -d @$tmpcfg2 -H "X-API-Key: $APIKEY"  $URL/rest/system/config \
+    || bail "CURL error $?. Unable to update JSON config on server" 
+  
+  res=`$CURLCMD -d '' -H "X-API-Key: $APIKEY"  $URL/rest/system/restart ` \
+    || bail "CURL error $?. Unable to update JSON config on server" 
+  [ "$VERBOSE" -eq 1 ] && echo RESULT=$res
+fi
 
-$CMD -d @$tmpcfg2 -H "X-API-Key: $APIKEY"  $URL/rest/system/config \
-  || bail "CURL error $?. Unable to update JSON config on server" 
-
-res=`$CMD -d '' -H "X-API-Key: $APIKEY"  $URL/rest/system/restart ` \
-  || bail "CURL error $?. Unable to update JSON config on server" 
-
-[ "$VERBOSE" -eq 1 ] && echo RESULT=$res
 
 rm -f $tmpcfg1 $tmpcfg2 $cooks
 
